-- MySql Dialect
CREATE TABLE twitter_status (id INT NOT NULL AUTO_INCREMENT, text VARCHAR(140) NOT NULL, sequence_no INT NOT NULL UNIQUE, tweeted_on TIMESTAMP NULL, PRIMARY KEY (id));
CREATE TABLE config (id VARCHAR(255) NOT NULL, active_on TIMESTAMP NULL, PRIMARY KEY (id));