-- MySql Dialect
CREATE TABLE tweet (id INT NOT NULL AUTO_INCREMENT, text VARCHAR(140) NOT NULL, sequence_no INT NOT NULL UNIQUE, tweeted_on TIMESTAMP NULL, PRIMARY KEY (id));
CREATE TABLE application_status (id VARCHAR(255) NOT NULL, active_on TIMESTAMP NULL, PRIMARY KEY (id));